name: dev
channels:
  - conda-forge
dependencies:
  - pandas==2.0.2
  - numpy==1.24.3
  - matplotlib==3.7.1
  - geos==3.11.2
  - Cartopy==0.21.1
  - pangaeapy==1.0.13
  - pycountry==22.3.5
  - pip:
    - countryinfo==0.1.2
